REM ******************************************************************
REM Fecha         : DD/MM/AAAA
REM Realizado por : Ownk
REM Base de Datos : [DATA_BASE]
REM ******************************************************************


REM TABLESPACE TEMPORAL

CREATE TEMPORARY TABLESPACE [TABLESPACE_NAME] TEMPFILE
'C:\app\OWNK\product\18.0.0\oradata\XE\TOWNK.dbf' SIZE 300m
         Extent management LOCAL uniform SIZE 2m
;


REM TABLESPACE DE DATOS

CREATE TABLESPACE TS_DOWNK DATAFILE 
  'C:\app\OWNK\product\18.0.0\oradata\XE\DOWNK.DBF' SIZE 300M AUTOEXTEND ON NEXT 1024M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


REM TABLESPACE DE INDICES 
                                                            
CREATE TABLESPACE TS_IOWNK DATAFILE 
  'C:\app\OWNK\product\18.0.0\oradata\XE\IOWNK.DBF' SIZE 300M AUTOEXTEND ON NEXT 1024M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;   

