REM USUARIO DEL APLICATIVO [USER_NAME]

ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

DROP USER [USER_NAME] CASCADE;

CREATE USER [USER_NAME]
 IDENTIFIED BY [USER_NAME]
 DEFAULT TABLESPACE [TABLESPACE_NAME]
 TEMPORARY TABLESPACE [TABLESPACE_NAME]
 ACCOUNT UNLOCK;


GRANT 
  ALTER USER, CREATE CLUSTER, CREATE DATABASE LINK, CREATE PROFILE , ALTER PROFILE, 
  CREATE PROCEDURE, CREATE PUBLIC DATABASE LINK, 
  CREATE PUBLIC SYNONYM, CREATE ROLE, CREATE SEQUENCE, 
  CREATE SESSION, CREATE SYNONYM, CREATE TABLE, 
  CREATE TRIGGER, CREATE USER , CREATE VIEW, CREATE TYPE,
  DROP PUBLIC SYNONYM, EXECUTE ANY PROCEDURE, 
  SELECT ANY SEQUENCE, SELECT ANY TABLE, 
  UNLIMITED TABLESPACE TO [USER_NAME];
