--
PROMPT
PROMPT LANZADOR PRINCIPAL
PROMPT
--

@@02_Tables/INSTALL_TABLES.sql
@@03_Primary_Key/INSTALL_PRIMARY_KEY.sql
@@04_Foreing_Key/INSTALL_FOREIGN_KEY.sql
@@05_Comments/INSTALL_COMMENTS.sql
@@06_Data/INSTALL_DATA.sql
@@07_Type/INSTALL_TYPES.sql
@@08_Package/INSTALL_PACKAGE.sql
@@09_Funcion/INSTALL_FUNCION.sql
@@10_Procedure/INSTALL_PROCEDURE.sql
@@11_Trigger/INSTALL_TRIGGER.sql
@@12_View/INSTALL_VIEW.sql
@@13_Index/INSTALL_INDEX.sql
